export const PREDEFINED_PERMISSIONS = [
  { code: 'sale.create', description: 'Create sales transactions' },
  { code: 'sale.view', description: 'View sales transactions' },
  { code: 'sale.void', description: 'Void sales transactions' },
  { code: 'sale.discount', description: 'Apply discounts' },
  { code: 'sale.return', description: 'Process sales returns' },
  { code: 'product.create', description: 'Create products' },
  { code: 'product.view', description: 'View products' },
  { code: 'product.edit', description: 'Edit products' },
  { code: 'product.delete', description: 'Delete products' },
  { code: 'stock.view', description: 'View stock' },
  { code: 'stock.adjust', description: 'Adjust stock' },
  { code: 'stock.transfer', description: 'Transfer stock' },
  { code: 'customer.create', description: 'Create customers' },
  { code: 'customer.view', description: 'View customers' },
  { code: 'customer.edit', description: 'Edit customers' },
  { code: 'report.view', description: 'View reports' },
  { code: 'report.export', description: 'Export reports' },
  { code: 'user.create', description: 'Create users' },
  { code: 'user.view', description: 'View users' },
  { code: 'user.edit', description: 'Edit users' },
  { code: 'user.delete', description: 'Delete users' },
  { code: 'business.edit', description: 'Edit business settings' },
  { code: 'shift.open', description: 'Open cash register shift' },
  { code: 'shift.close', description: 'Close cash register shift' },
] as const;

export const PREDEFINED_ROLES = {
  admin: {
    name: 'Admin',
    permissions: [
      'sale.create',
      'sale.view',
      'sale.void',
      'sale.discount',
      'sale.return',
      'product.create',
      'product.view',
      'product.edit',
      'product.delete',
      'stock.view',
      'stock.adjust',
      'stock.transfer',
      'customer.create',
      'customer.view',
      'customer.edit',
      'report.view',
      'report.export',
      'user.create',
      'user.view',
      'user.edit',
      'user.delete',
      'business.edit',
      'shift.open',
      'shift.close',
    ],
  },
  cashier: {
    name: 'Cashier',
    permissions: [
      'sale.create',
      'sale.view',
      'product.view',
      'stock.view',
      'customer.create',
      'customer.view',
      'shift.open',
      'shift.close',
    ],
  },
} as const;
